### PR TITLE
Briefly describe motivations for these materials

### PR DESCRIPTION
**Pull request by robmoss**
The introduction page explains what the materials contain, but didn't explain why these skills and practices are useful.

My aim was to keep this short, and briefly explain the concrete value of the different sections.

### CODE REVIEW

**Review by EamonConway — COMMENTED** [review]
I think we could even have the motivation front and centre and not hidden away in a different section.
It highlights a lot of amazing points that researchers should consider but currently arent.

**Comment by robmoss** [comment]
Good point @EamonConway. I didn't want to make the landing page too long, but I agree that it's good to make these things as visible as possible.

**Comment by robmoss** [comment]
@EamonConway I've moved the content to the front page and I like it. Thanks for the suggestion!

**Comment by EamonConway** [comment]
I am happy for this to be merged into master.

**Pull request merged**
