### PR TITLE
Update how-to-ignore-certain-files.md

### PR DESCRIPTION
**Pull request by iabell**
Added in a tip about using the touch command if you cannot create a file named ".gitignore"

### CODE REVIEW

**Comment by robmoss** [comment]
Thanks very much for this @iabell. I'd suggest one small change: instead of "If your **system** will not ...", we should probably say "If your **editor** will not ...".

Also, please add yourself to `src/contributors.md` and link to your github profile (similar to the other contributors listed in that file).

FYI, I enabled the CI pipeline and the failure is *expected* --- we can build the book with your changes (that step succeeded), but we can't publish it from your fork.

**Comment by iabell** [comment]
Thanks Rob - I've added in your edit and will add myself to the contributors page

**Comment by robmoss** [comment]
> Thanks Rob - I've added in your edit and will add myself to the contributors page

Feel free to do this with a final commit for this PR :)

**Comment by robmoss** [comment]
Thank you very much @iabell!

**Pull request merged**
