### PR TITLE
Draft notes for our August meeting

### PR DESCRIPTION
**Pull request by robmoss**
I've also added links to relevant topical guide content in the orientation guide.

### CODE REVIEW

**Comment by robmoss** [comment]
@EamonConway @jomonman537 I've pushed my draft notes for yesterday's meeting, here's the [online preview](https://git-is-my-lab-book.net/pr-preview/pr-74/community/meetings/2024-08-08/).

**Comment by robmoss** [comment]
Once we publish the finalised notes for this meeting, we should let everyone know that we **will** run an Introduction to Debugging workshop at the SPECTRUM annual meeting :)

**Comment by jomonman537** [comment]
I had a look through the meeting notes and made some minor corrections. Other than that, the contents of the meeting notes are mostly correct.

In the GPGPU section of the meeting notes, I noticed that you used "multiple CPUs to make code run more quickly". Do you mean "multiple CPU cores" or "multiple CPUs"? I don't think it is possible to run a computer over multiple CPUs (unless you are talking about a workstation or server farm).

**Comment by robmoss** [comment]
Thanks very much @James.

Unless you're really pushing against hardware limitations, from an end-user perspective there's very little difference between (a) multiple cores in a single CPU, with shared cache; and (b) multiple CPUs with independent caches (Intel has a nice diagram, see [Figure 2](https://www.intel.com/content/www/us/en/developer/articles/tool/performance-counter-monitor.html)). In either case, the relevant feature is that each core can run a separate process.

The approaches we discussed in the meeting readily apply to both situations, and it's only when we need to use more complex approaches that the distinction matters. I chose to say "CPU" rather than "CPU core" because I feel that most people have at least a vague notion of what a CPU is, and I thought that saying "CPU core" might be more confusing ... :shrug:. What do you think is best?

```diff
-    There was strong interest [...] based on **our** own experiences.
+    There was strong interest [...] based on **their** own experiences.
```

I've tended to use "them", "they", etc, to refer to individual attendees or the attendees as a whole. For this specific remark about recommending packages and libraries, I wanted to refer to our community as a whole — using our collective experiences to make these recommendations. So I'd prefer to leave it as "our own experiences". Does that seem reasonable to you?

**Comment by jomonman537** [comment]
> The approaches we discussed in the meeting readily apply to both situations, and it's only when we need to use more complex approaches that the distinction matters. I chose to say "CPU" rather than "CPU core" because I feel that most people have at least a vague notion of what a CPU is, and I thought that saying "CPU core" might be more confusing ... 🤷. What do you think is best?

According to Figure 2, it seems we can distinguish between a CPU processor and a CPU core. When I think of parallel computing at the consumer level, using multiple CPU cores is more understandable to me than using multiple CPU processors. And as all CPUs nowadays use multiple cores rather than a single core, from my perspective it should be fine to use CPU cores than CPUs or CPU processors.

> I've tended to use "them", "they", etc, to refer to individual attendees or the attendees as a whole. For this specific remark about recommending packages and libraries, I wanted to refer to our community as a whole — using our collective experiences to make these recommendations. So I'd prefer to leave it as "our own experiences". Does that seem reasonable to you?

That should be fine. It implies that we had a group discussion on packages and libraries multiple people recommended than one person proposing ideas from their own experience.

**Comment by robmoss** [comment]
Thanks @James, I've used "CPU core" / "CPU cores" throughout, and restored "our own experiences". @EamonConway are you happy for me to merge this?

**Pull request merged**
