### PR TITLE
Divide into several top-level sections

### PR DESCRIPTION
**Pull request by robmoss**
The proposed orientation guide should probably be in a separate section from the topic-specific materials we've developed so far. To that end, I've divided the content into the following sections:

- Introduction: as per the original home page, and also containing the "How to contribute" and "Contributors" pages.

- Orientation: a new section for the orientation guide.

- Topical guides: the current training materials, except case studies.

- Community: the Community of Practice meetings, and the case studies, since they're standalone contributions from the community.

I've also enabled the "navigation.tabs" and "navigation.tabs.sticky" features, so that these top-level sections are rendered in a menu layer below the header (except for mobile devices).

### CODE REVIEW

**Comment by robmoss** [comment]
The aim of this pull request is to give us a starting point for developing the orientation guide in collaboration with the broader CoP.

**Comment by jomonman537** [comment]
The layout of the resource is cleaner than the original version, with less sections under the section list on the left. I wonder if you could include a brief section within the 'introduction' tab outlining what the other tabs on top contain and what audience they are targeting. It is not obvious from my perspective that 'orientation' is a reproducible research introduction/checklist while 'topical guides' represents the main content of Git is my Lab Book.

I also wonder if the text within the boxes (e.g., Question, Foundations of effective research) could be made bigger so that it is the same size as the main text. I struggle to read the text that is contained within the boxes compared to the main text. Smaller text in the boxes might make it difficult for readers to get a full understanding of the content within the page.

**Comment by robmoss** [comment]
> I also wonder if the text within the boxes (e.g., Question, Foundations of effective research) could be made bigger so that it is the same size as the main text. I struggle to read the text that is contained within the boxes compared to the main text. Smaller text in the boxes might make it difficult for readers to get a full understanding of the content within the page.

Hi @jomonman537, I also found this smaller font size to be undesirable. I found a solution [here](https://github.com/squidfunk/mkdocs-material/discussions/2260) and have pushed a commit that ensures that admonitions now have the same font size as the regular page content.

**Comment by robmoss** [comment]
> The layout of the resource is cleaner than the original version, with less sections under the section list on the left. I wonder if you could include a brief section within the 'introduction' tab outlining what the other tabs on top contain and what audience they are targeting. It is not obvious from my perspective that 'orientation' is a reproducible research introduction/checklist while 'topical guides' represents the main content of Git is my Lab Book.

Inspired by the [Scientific Python Library Development Guide ](https://learn.scientific-python.org/development/), I've added a brief description of each top-level section at the start of the Introduction page. How does this look?

**Comment by jomonman537** [comment]
Great; thanks for responding to my comments. I can confirm that I can see the text within the boxes and also an overview of the structure of the resource. I have pushed a commit to capitalise the first letter after the colon of each structure dotpoint so that it is consistent with the [Scientific Python Library Development Guide](https://learn.scientific-python.org/development/).

I am happy for you to push the branch onto the main branch so that we can update the Git is my Lab Book resource.

**Comment by EamonConway** [comment]
I really enjoy the new layout, it looks great. 
I am nervous about the suggested topic of How to set up common tools on your laptop (e.g., Python and R). 
I feel like this may be opening up a can of worms that we do not want to, for example operating systems and institutional security policies. 
Should we perhaps just provide a link to helpful resources?

**Comment by robmoss** [comment]
> I am nervous about the suggested topic of How to set up common tools on your laptop (e.g., Python and R). I feel like this may be opening up a can of worms that we do not want to, for example operating systems and institutional security policies. Should we perhaps just provide a link to helpful resources?

Agreed, we should definitely point to external resources for these kinds of things! Similar to how we only teach how to use Git from the command-line, and link to GUIs and other tools.

**Comment by robmoss** [comment]
@EamonConway if you're happy for me to merge this, I'll go ahead and then rebase #66 to apply cleanly on top of it.

**Comment by EamonConway** [comment]
> @EamonConway if you're happy for me to merge this, I'll go ahead and then rebase #66 to apply cleanly on top of it.

Sounds like a plan.

**Pull request merged**
