### PR TITLE
Section/collaboration: initial draft of each chapter

### PR DESCRIPTION
**Pull request by robmoss**
I've written an initial draft for each chapter in this section, covering things such as how to structure a repository, how to use pull requests, and how to conduct peer code review. I've also suggested some high-level guidelines for working collaboratively on code and writing papers.

- I feel like this section could use some simple examples to demonstrate the main concepts. We could even link to this pull request as an example of using pull requests to review changes before merging them!

- I think the chapters are ordered sensibly, but it would be great to hear your thoughts.

- Some chapters are quite brief, so please let me know if you feel that any important points or details are missing.

- Please let me know if you have any ideas for further guidelines or suggestions for the "Collaborating on code" and "Collaborating on a paper" chapters.

- Perhaps the easiest way to review this would be to clone this branch and build the book locally, so that you can view the published version in your browser?

  - That might be a good idea anyway, to verify that the "Building the book" instructions in `README.md` are correct and complete.

### CODE REVIEW

**Comment by EamonConway** [comment]
I think including this pull request as an example is a great idea. 

In regards to the sections, I wonder if we move "How to structure a repo" and "Choosing a license" into a seperate section. I would argue that these two topics are independent of collaboration and might be more suited to different sections? I think that "How to structure a repo" would be suited to effective use of git. I think if we do that, we can start the Collaboration section with "Collaborating on code". As this section is really just a broad overview it really provides a good starting point on collaboration. 

I followed the "Building the book" instructions, and they are definitely enough for me. Depending on the audience we might have some problems though. I'm not sure how many people are comfortable with installing software using package managers and command line? We could add a step by step instruction for those that do not have rust installed?

**Comment by robmoss** [comment]
> I think including this pull request as an example is a great idea.

Great! Now that it's been created, I can link to it from the book chapters. I'll have a think about where and how we might want to do this.

> In regards to the sections, I wonder if we move "How to structure a repo" and "Choosing a license" into a seperate section. I would argue that these two topics are independent of collaboration and might be more suited to different sections? I think that "How to structure a repo" would be suited to effective use of git. I think if we do that, we can start the Collaboration section with "Collaborating on code". As this section is really just a broad overview it really provides a good starting point on collaboration.

Agreed, that makes a lot of sense. I'll make that change in this PR.

> I followed the "Building the book" instructions, and they are definitely enough for me. Depending on the audience we might have some problems though. I'm not sure how many people are comfortable with installing software using package managers and command line? We could add a step by step instruction for those that do not have rust installed?

Good point about adding step-by-step instructions. All of the dependencies (mdBook, mdbook-admonish, and mdbook-linkcheck) are available as pre-compiled binaries for Windows, Mac, and Linux, so thankfully it's a very simple process. I suppose these instructions should appear in `README.md` **and** in the book itself. That should probably be a separate PR.

**Comment by robmoss** [comment]
I've added a new chapter, "An example pull request", to show how we're using this pull request to draft the chapters in the "Collaborating" section. I've added it between the "Merge/Pull request" chapter and the "Peer code review" chapter, because I think it might be helpful for readers to see a concrete example before talking about using pull requests for peer code review.

**Review by EamonConway — COMMENTED** [review]
I think this section has developed really well. I'm very happy for it to become part of the master branch.

**Pull request merged**
