### PR TITLE
Add Project structure and Writing code sections

### PR DESCRIPTION
**Pull request by robmoss**
I started sketching out content for a project structure section, but this quickly branched out to include a variety of topics that are better described as writing code.

Sources of motivation include:

- Having some content about choosing a project structure ahead of the next malaria group meeting, when we're going to talk about this topic;
- Writing down my key arguments for considering code as a primary research output; and
- Explaining why the way that we approach writing code, and learning to write code, is extremely important.

I want to refer to real examples of public repositories (such as my [2020 COVID-19 forecasts one](https://gitlab.unimelb.edu.au/rgmoss/aus-2020-covid-forecasts), which I mention in [Project structure / Explain how it all works](https://git-is-my-lab-book.net/pr-preview/pr-59/project-structure/explain-how-it-works.html)) and highlight what they do well and what they don't do well.

### CODE REVIEW

**Comment by robmoss** [comment]
... and now it occurs to me that I should probably end the "Writing code" section with a reminder, or an exercise, to seek feedback on code that you're currently writing (i.e., code that isn't finished) ...

**Comment by robmoss** [comment]
[Scientific Python](https://scientific-python.org/) provides helpful guides on a number of [relevant topics](https://learn.scientific-python.org/development/), including some general [design principles](https://learn.scientific-python.org/development/principles/design/). Some of the [topical guides](https://learn.scientific-python.org/development/guides/) are very detailed and, perhaps, a bit too much detail for our audience.

**Comment by robmoss** [comment]
We should share this PR with the CoP and ask them to provide suggestions, comments, etc, building on what we covered in yesterday's meeting. We can provide the live preview of the [Project structure](https://git-is-my-lab-book.net/pr-preview/pr-59/project-structure/index.html) and [Writing code](https://git-is-my-lab-book.net/pr-preview/pr-59/writing-code/index.html) sections.

**Comment by robmoss** [comment]
@EamonConway I've migrated this PR from mdBook to MkDocs

As per my previous comment, we should consider sharing this PR with the CoP and ask them to provide suggestions, comments, etc. It probably covers some things that are relevant to the orientation guide.

**Comment by robmoss** [comment]
I've rebased this so that it applies cleanly on the new site structure (Introduction / Orientation / Topical Guides / Community).

**Comment by michaelplanknz** [comment]
Sorry git novice here so not sure if this is the right place to post this!

As a suggestion for the Orientation section (which already looks super useful), it might be useful to have a few examples of code that are small and self-contained and do some simple task. For example, a function that reads in a long-form CSV data set and returns some aggregated values, e.g. number of occurrences of X on each day between Y and Z. This could serve as an exemplar for how to structure good code (comments, good variable naming, no magic numbers, well defined function inputs/outputs, etc.). It could also include an example of a test function, as I think the idea of automated tests may be a new concept for many (me included!). Ideally, keeping the tasks relatively simple will mean that code doesn't need to use too many language-specific features or packages but can illustrate principles in a language-agnostic way.
 
Again apologies if this is in the wrong place, please feel free to tell me if I should post this somewhere else!

**Comment by robmoss** [comment]
Hi @michaelplanknz that's a great suggestion! Having examples that show rather than tell would be really useful.

I've created a new issue #69 to act as a starting point, because it's not directly related to this pull request (absolutely no drama, and apologies for not having clearer instructions on the orientation guide page itself).

**Comment by robmoss** [comment]
@EamonConway can you please let me know if you're happy for me to merge this?

**Comment by robmoss** [comment]
@EamonConway mind you, I could probably cut down the [cake analogy](https://git-is-my-lab-book.net/pr-preview/pr-59/guides/writing-code/behave-nicely/)

**Comment by robmoss** [comment]
@EamonConway I've revised the cake analogy and added two more specific tips [at the end](https://git-is-my-lab-book.net/pr-preview/pr-59/guides/writing-code/behave-nicely/#some-specific-tips).

**Comment by robmoss** [comment]
Hmm, the [Coding Advice](https://git-is-my-lab-book.net/pr-preview/pr-59/guides/writing-code/coding-advice/) page could probably do with a few (very short) code examples too.

**Comment by robmoss** [comment]
@EamonConway I'm going to merge this in advance of our next CoP meeting, as we discussed yesterday. Thanks!

**Pull request merged**
