### PR TITLE
Update contributors.md

### PR DESCRIPTION
**Pull request by nefeltellioglu**
Updated my surname in the document

### CODE REVIEW

**Comment by robmoss** [comment]
Hi @nefeltellioglu, sorry I didn't get it right! Did you mean to close this PR, or would you like us to accept this change?

**Comment by nefeltellioglu** [comment]
Hi Rob, sorry I closed this by mistake! I would like to update my name as "Nefel Tellioglu"

**Comment by robmoss** [comment]
@nefeltellioglu and it's [updated online](https://git-is-my-lab-book.net/contributors/)

**Comment by nefeltellioglu** [comment]
Thanks, Rob!

Bests,
Nefel

**Pull request merged**
