### PR TITLE
Notes for meeting on 15 August 2023

### PR DESCRIPTION
**Pull request by robmoss**
Here are my draft notes for today's meetings. Links to useful resources that were mentioned during the meeting are provided in the Resources section at the bottom of the page. Feedback and thoughts welcome!

### CODE REVIEW

**Comment by jomonman537** [comment]
Seems like a lot of resources and insights shared in yesterday's CoP meeting. I don't have any comments to add on the notes written.

It would be good to organise a resource list in the future that puts together the resources that are shared in the CoP meetings. This can act as a central repository that is updated regularly  in which community members can learn more information about reproducible research. What do you think?

**Comment by robmoss** [comment]
Hi @jomonman537 we do have links to various resources at the end of the book ([References](https://git-is-my-lab-book.net/references.html)), although this probably isn't terribly discoverable. One alternative would be to add a new chapter (called, say, "Useful Resources") at the end of each section ("Version control concepts", "Effective use of git", "Collaborating", etc).

**Comment by jomonman537** [comment]
That would be good to add a resource page at the end of each chapter, but I think the resources lists would be too well-hidden. Alternatively, it might be better to have a separate chapter that appears on the sidebar at the end of the book, where readers can see a single list of resources that is split into different topics. What do you think?

**Comment by robmoss** [comment]
I agree in principle, but how do you see that differing from the current References chapter? Is it simply a matter of renaming it to something like "Useful Resources", or did you have something else in mind?

**Comment by jomonman537** [comment]
Oh, sorry, didn't see that references had some useful resources. When I read 'references', I got the impression that it was a bibliography of stuff that was cited in the website, not a list of useful resources. I would perhaps change 'references' to 'useful resources' and add additional resources that might be helpful from the CoP meetings to that page.

**Comment by robmoss** [comment]
Thanks @jomonman537, I'll rename the References section and restructure it the next few days.

**Pull request merged**
