### PR TITLE
Migrate from mdBook to Material for MkDocs

### PR DESCRIPTION
**Pull request by robmoss**
Material for MkDocs provides lots of [desirable features](https://squidfunk.github.io/mkdocs-material/reference/), from tabbed content blocks to responsive layouts, and is used by many projects.

### CODE REVIEW

**Comment by EamonConway** [comment]
I am happy for this to be merged. 
I have a couple of minor comments we might want to address. 

The terminal is enormous on my screen, can we change the format? I feel like it used to be better or is that just an issue on my machine? Eg, https://git-is-my-lab-book.net/pr-preview/pr-65/using-git/choosing-your-git-editor/ 
The git is my lab book header at the top used to link back to the introduction, but no longer does.

**Comment by robmoss** [comment]
> I am happy for this to be merged. I have a couple of minor comments we might want to address.

Brilliant, thanks!

> The terminal is enormous on my screen, can we change the format? I feel like it used to be better or is that just an issue on my machine? Eg, https://git-is-my-lab-book.net/pr-preview/pr-65/using-git/choosing-your-git-editor/

Good question. It looks like mdBook had a narrower content column. I'll see if I can decrease the `max-width` for asciinema videos.

> The git is my lab book header at the top used to link back to the introduction, but no longer does.

Darn, I'm not sure we can change that. The logo does, however, link back to the introduction.

**Comment by robmoss** [comment]
Hmm ... decreasing `max-width` shrinks the video pane, but that simply cuts off long lines, and decreasing the font size shrinks the terminal output, but the video pane remains the same width. A quick search of the [asciinema-player](https://github.com/asciinema/asciinema-player/) issue tracker doesn't reveal anything helpful.

No easy answer, as far as I can tell. Perhaps best to leave it as-is for now?

**Comment by EamonConway** [comment]
> Hmm ... decreasing `max-width` shrinks the video pane, but that simply cuts off long lines, and decreasing the font size shrinks the terminal output, but the video pane remains the same width. A quick search of the [asciinema-player](https://github.com/asciinema/asciinema-player/) issue tracker doesn't reveal anything helpful.
> 
> No easy answer, as far as I can tell. Perhaps best to leave it as-is for now?

I am happy with this, everything is just larger than before which is fine.

**Pull request merged**
